name: "100xChat"
version: "1.0"
services:
  backend:
    build:
      context: ./backend
    container_name: "100xChat-backend"
    ports:
      - "3000:3000"
    volumes :
      - ./backend:/backend
      - /backend/node_modules
  frontend:
    build:
      context: ./frontend
    container_name: "100xChat-frontend"
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
